<?php

//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <https://www.xoops.org>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

$modversion['name'] = 'FatalQuery';
$modversion['version'] = '1.75';
$modversion['description'] = _MI_FQ_DESC;
$modversion['author'] = 'NSN-Nuke Interface was Written by nobleclem (FatalException Crew). Server QueryCode (madquery.php) was Written by MadCoder';
$modversion['credits'] = 'Jon L. ( http://www.csmapcentral.com/ )<br>Alan K.( http://kockelbergh.ath.cx/~alank/ )';
$modversion['help'] = '';
$modversion['license'] = 'GNU/GPL';
$modversion['official'] = 0;
$modversion['image'] = 'images/admin/fatalquery.png';
$modversion['dirname'] = 'fatalquery';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'fatalquery_maps';
$modversion['tables'][1] = 'fatalquery_svrs';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Blocks
$modversion['blocks'][1]['file'] = 'fatalquery.php';
$modversion['blocks'][1]['name'] = 'FatalQuery Server Listing';
$modversion['blocks'][1]['description'] = 'Shows server listing overviews in a small block interface.';
$modversion['blocks'][1]['show_func'] = 'b_fatalquery_servers_show';
$modversion['blocks'][1]['template'] = 'fatalquery_servers.html';

// Menu
$modversion['hasMain'] = 1;
global $xoopsDB, $xoopsModuleConfig;
$result = $xoopsDB->query('SELECT * from ' . $xoopsDB->prefix('fatalquery_svrs') . ' ORDER BY `svr_id`');
$i = 1;
while (list($svr_id, $svr_name) = $xoopsDB->fetchRow($result)) {
    if ($i != $xoopsModuleConfig['user_query_id']) {
        $modversion['sub'][$i]['name'] = $svr_name;

        $modversion['sub'][$i]['url'] = 'index.php?op=userquery&svrid=' . $svr_id;
    }

    $i++;
}
$modversion['sub'][$i]['name'] = _MI_FQ_SMNAME1;
$modversion['sub'][$i]['url'] = 'index.php?op=maps';

// Config Settings (only for modules that need config settings generated automatically)

// name of config option for accessing its specified value. i.e. $xoopsModuleConfig['storyhome']
$modversion['config'][1]['name'] = 'user_query_id';
// title of this config option displayed in config settings form
$modversion['config'][1]['title'] = '_MI_FQ_ADMIN_USER_QUERY_ID';
// description of this config option displayed under title
$modversion['config'][1]['description'] = '_MI_FQ_ADMIN_USER_QUERY_ID_DESC';
// form element type used in config form for this option. can be one of either textbox, textarea, select, select_multi, yesno, group, group_multi
$modversion['config'][1]['formtype'] = 'textbox';
// value type of this config option. can be one of either int, text, float, array, or other
// form type of 'group_multi', 'select_multi' must always be 'array'
// form type of 'yesno', 'group' must be always be 'int'
$modversion['config'][1]['valuetype'] = 'int';
// the default value for this option
// ignore it if no default
// 'yesno' formtype must be either 0(no) or 1(yes)
$modversion['config'][1]['default'] = '1';
// options to be displayed in selection box
// required and valid for 'select' or 'select_multi' formtype option only
// language constants can be used for both array keys and values
//$modversion['config'][1]['options'] = array('5' => 5, '10' => 10, '50' => 50, '100' => 100, '200' => 200, '500' => 500, '1000' => 1000);

$modversion['config'][2]['name'] = 'right_blocks';
$modversion['config'][2]['title'] = '_MI_FQ_ADMINRTBLOCKS';
$modversion['config'][2]['description'] = 'right blocks';
$modversion['config'][2]['formtype'] = 'yesno';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = '1';

$modversion['config'][3]['name'] = 'page_title';
$modversion['config'][3]['title'] = '_MI_FQ_ADMINPGTITLE';
$modversion['config'][3]['description'] = 'This text will appear at the top of the page';
$modversion['config'][3]['formtype'] = 'textbox';
$modversion['config'][3]['valuetype'] = 'text';
$modversion['config'][3]['default'] = '<b>Server Listing</b>';

$modversion['config'][4]['name'] = 'default_view';
$modversion['config'][4]['title'] = '_MI_FQ_ADMINDEFAULTVIEW';
$modversion['config'][4]['description'] = 'Default page View';
$modversion['config'][4]['formtype'] = 'select';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = '1';
$modversion['config'][4]['options'] = [ '_MI_FQ_ADMINDVFULL' => 1, '_MI_FQ_ADMINDVSHORT' => 0];

$modversion['config'][5]['name'] = 'maps_in_row';
$modversion['config'][5]['title'] = '_MI_FQ_ADMINMAPSINROW';
$modversion['config'][5]['description'] = 'Maps in row';
$modversion['config'][5]['formtype'] = 'textbox';
$modversion['config'][5]['valuetype'] = 'int';
$modversion['config'][5]['default'] = '3';

$modversion['config'][6]['name'] = 'default_pic_name';
$modversion['config'][6]['title'] = '_MI_FQ_ADMINDEFAULTPIC';
$modversion['config'][6]['description'] = 'Default Pic Name';
$modversion['config'][6]['formtype'] = 'textbox';
$modversion['config'][6]['valuetype'] = 'text';
$modversion['config'][6]['default'] = 'nopicavail';

$modversion['config'][7]['name'] = 'map_heading_1';
$modversion['config'][7]['title'] = '_MI_FQ_ADMINHEADING1';
$modversion['config'][7]['description'] = 'Map Page Heading 1';
$modversion['config'][7]['formtype'] = 'textbox';
$modversion['config'][7]['valuetype'] = 'text';
$modversion['config'][7]['default'] = 'Current Maprotation';

$modversion['config'][8]['name'] = 'map_heading_2';
$modversion['config'][8]['title'] = '_MI_FQ_ADMINHEADING2';
$modversion['config'][8]['description'] = 'Map Page Heading 2';
$modversion['config'][8]['formtype'] = 'textbox';
$modversion['config'][8]['valuetype'] = 'text';
$modversion['config'][8]['default'] = 'Available Maps';

$modversion['config'][9]['name'] = 'map_pic_dir';
$modversion['config'][9]['title'] = '_MI_FQ_ADMINMAPPICDIR';
$modversion['config'][9]['description'] = 'Map Picture Directory';
$modversion['config'][9]['formtype'] = 'textbox';
$modversion['config'][9]['valuetype'] = 'text';
$modversion['config'][9]['default'] = 'map_pics/';

$modversion['config'][10]['name'] = 'mappic_ext';
$modversion['config'][10]['title'] = '_MI_FQ_ADMINMAPPICEXT';
$modversion['config'][10]['description'] = 'Map Picture Extension';
$modversion['config'][10]['formtype'] = 'select';
$modversion['config'][10]['valuetype'] = 'text';
$modversion['config'][10]['default'] = '.gif';
$modversion['config'][10]['options'] = ['.gif' => '.gif', '.png' => '.png', '.jpg' => '.jpg', '.jpeg' => '.jpeg'];

$modversion['config'][11]['name'] = 'map_dl_location';
$modversion['config'][11]['title'] = '_MI_FQ_ADMINMAPDLLOCATION';
$modversion['config'][11]['description'] = '_MI_FQ_ADMINMAPDLLOCATION_DESC';
$modversion['config'][11]['formtype'] = 'textbox';
$modversion['config'][11]['valuetype'] = 'text';
$modversion['config'][11]['default'] = '/home/username/hlds_l/valve/maps';

$modversion['config'][12]['name'] = 'map_dl_ext';
$modversion['config'][12]['title'] = '_MI_FQ_ADMINMAPDLEXT';
$modversion['config'][12]['description'] = 'Map Download Extension';
$modversion['config'][12]['formtype'] = 'select';
$modversion['config'][12]['valuetype'] = 'text';
$modversion['config'][12]['default'] = '.bsp';
$modversion['config'][12]['options'] = ['.zip' => '.zip', '.tar' => '.tar', '.tgz' => '.tgz', '.tar.gz' => '.tar.gz', '.bsp' => '.bsp'];

$modversion['config'][13]['name'] = 'user_query';
$modversion['config'][13]['title'] = '_MI_FQ_ADMINUSERQUERY';
$modversion['config'][13]['description'] = 'User Query Fields';
$modversion['config'][13]['formtype'] = 'yesno';
$modversion['config'][13]['valuetype'] = 'int';
$modversion['config'][13]['default'] = '0';

$modversion['config'][14]['name'] = 'custom_on';
$modversion['config'][14]['title'] = '_MI_FQ_ADMINCUSTOMCODE';
$modversion['config'][14]['description'] = 'Custom Code';
$modversion['config'][14]['formtype'] = 'yesno';
$modversion['config'][14]['valuetype'] = 'int';
$modversion['config'][14]['default'] = '1';

$modversion['config'][15]['name'] = 'map_dl_link';
$modversion['config'][15]['title'] = '_MI_FQ_ADMINMAPDLLINK';
$modversion['config'][15]['description'] = 'Map Downloads Link';
$modversion['config'][15]['formtype'] = 'yesno';
$modversion['config'][15]['valuetype'] = 'int';
$modversion['config'][15]['default'] = '0';

$modversion['config'][16]['name'] = 'custom_code';
$modversion['config'][16]['title'] = '_MI_FQ_ADMINEDITCUSTOMTITLE';
$modversion['config'][16]['description'] = '_MI_FQ_ADMINCUSTOMNOTE';
$modversion['config'][16]['formtype'] = 'textarea';
$modversion['config'][16]['valuetype'] = 'text';
$modversion['config'][16]['default'] = '<center>FatalQuery is a module for PHP-Nuke developed and maintained by nobleclem at <a href="http://www.fatalexception.us" target="_blank">www.fatalexception.us</a><br><a href="http://www.fatalexception.us/modules.php?name=Content&pa=showpage&pid=1" target="_blank">Click Here For Information About FatalQuery</a></center>';

// Templates
$modversion['templates'][1]['file'] = 'fatalquery_custom_code.html';
$modversion['templates'][1]['description'] = 'Custom Code';
$modversion['templates'][2]['file'] = 'fatalquery_default_view_short.html';
$modversion['templates'][2]['description'] = 'Compact serverlist';
$modversion['templates'][3]['file'] = 'fatalquery_default_view_full.html';
$modversion['templates'][3]['description'] = 'Full serverlist';
$modversion['templates'][4]['file'] = 'fatalquery_index.html';
$modversion['templates'][4]['description'] = 'Index';
$modversion['templates'][5]['file'] = 'fatalquery_maps.html';
$modversion['templates'][5]['description'] = 'Map List';
$modversion['templates'][6]['file'] = 'fatalquery_page_title.html';
$modversion['templates'][6]['description'] = 'Page Title';
$modversion['templates'][7]['file'] = 'fatalquery_query_server.html';
$modversion['templates'][7]['description'] = 'Server Info';
$modversion['templates'][8]['file'] = 'fatalquery_toplinks.html';
$modversion['templates'][8]['description'] = 'Top Links';
$modversion['templates'][9]['file'] = 'fatalquery_userquery.html';
$modversion['templates'][9]['description'] = 'User Query';
